### ISSUE TITLE
Update Audiere

### ISSUE THREAD

**Issue by terinjokes** [terinjokes/mixere#3]
Mixere relies heavily on the audio file and playback library [Audiere](https://audiere.sourceforge.net/). Like Mixere, Audiere hasn't had a release in over a decade, which is somewhat concerning in the scary world of 2021's internet. We also currently only have 32-bit versions of audiere.dll, which will cause problems for #2.

**Comment by terinjokes** [comment]
It looks like there's a somewhat [modernized fork](https://github.com/poikilos/Audiere) available, which has tagged a 1.10.0 release. It looks like most of the effort so far has been on the Linux side of things so far, but:

> implement fixes for MSVC 32-bit & 64-bit compilation

I don't think it makes sense to maintain my own fork, but the Visual Studio solutions are pretty old at this point. Would you be accepting of Windows-focused patches @poikilos?

**Comment by Poikilos** [comment]
Sure!
